// CommonJs, Every file is a module (by default)
// Modules - Encapsulated code (only share minimum)
const names = require('./4-names')
const sayHi = require('./5-utils.js')
const data = require('./6-alternative-export')
console.log(data)
require('./min-grenade')
sayHi(names.mario)
console.log(names)